# Generated by c.py
# Atul Varma (Spring 2004)

    .text
    .global main
main:
  pushl %ebp
  movl %esp, %ebp
  subl $8, %esp
  leal -4(%ebp), %edx
  movl $10, (%edx)
  movl (%edx), %ecx
  leal -8(%ebp), %ecx
  movl $11, (%ecx)
  movl (%ecx), %edx
  movl -4(%ebp), %edx
  cmpl $10, %edx
  setle %dl
  movzbl %dl, %edx
  testl %edx, %edx
  jz .L2_else
  movl -4(%ebp), %edx
  pushl %edx
  movl $LC0, %edx
  pushl %edx
  call printf
  addl $8, %esp
  leal -4(%ebp), %eax
  movl -4(%ebp), %edx
  addl $1, %edx
  movl %edx, (%eax)
  movl (%eax), %ecx
  jmp .L1_done
.L2_else:
  movl $LC1, %ecx
  pushl %ecx
  call printf
  addl $4, %esp
.L1_done:
  movl $0, %eax
  jmp .L0_function_end
.L0_function_end:
  movl %ebp, %esp
  popl %ebp
  ret

.global_vars:

LC0:
  .ascii "%d\0"
LC1:
  .ascii "bye\0"

